### ISSUE TITLE
'GetItemTemplateNameFromVSTemplatePath' task failed unexpectedly

### ISSUE THREAD

**Issue by gwin003** [ligershark/template-builder#64]
I just randomly started seeing this error while compiling my Template project. I have checked all my filenames and files for odd characters and everything is fine there, yet this error persists.

    Error	1	The "GetItemTemplateNameFromVSTemplatePath" task failed unexpectedly.
    System.ArgumentException: Illegal characters in path.
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
       at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
       at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
       at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
       at System.IO.FileInfo..ctor(String fileName)
       at LigerShark.TemplateBuilder.Tasks.GetItemTemplateNameFromVSTemplatePath.Execute()
       at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
       at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()	Templates

What can I do to further debug this? What else could be causing this?

**Comment by luismts** [comment]
Any solution on this?

**Comment by sayedihashimi** [comment]
I believe you can get this error if there is no `.vstemplate` file discovered.
